name: readily_reads
description: A reading habit tracker application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State management
  provider: ^6.0.5
  
  # Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # UI utilities
  flutter_slidable: ^3.0.0
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  
  # Date and time
  table_calendar: ^3.0.9
  
  # Charts
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Uncomment these when you have assets
  # assets:
  #   - assets/images/
  
  # Uncomment these when you have custom fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700